export const UserProductCollectionTypes = {
    SET_CURRENT_PRODUCT_LIST:"SET_CURRENT_PRODUCT_LIST",
    UPDATE_CURRENT_PRODUCT_LIST : "UPDATE_CURRENT_PRODUCT_LIST",
    DELETE_PRODUCT_FROM_LIST : "DELETE_PRODUCT_FROM_LIST"
}